.TH SMSC-CLI "1" "June 2016" "SMScoin-cli 0.12"
.SH NAME
SMScoin-cli \- a remote procedure call client for SMScoin. 
.SH SYNOPSIS
SMScoin-cli [options] <command> [params] \- Send command to SMScoin. 
.TP
SMScoin-cli [options] help \- Asks SMScoin for a list of supported commands.
.SH DESCRIPTION
This manual page documents the SMScoin-cli program. SMScoin-cli is an RPC client used to send commands to SMScoin.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBSMScoind\fP, \fBSMScoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
